import { MyText, MyButton, Title } from "framework/widgets.slint";
import { FrameworkState, OtaState } from "framework/framework.slint";
import { AppState, AppBackend } from "./app.slint";

component RectText inherits Rectangle {
    background: white;
    border-color: black;
    border-width: 1px;
    in property <string> text;
    VerticalLayout {
        padding-top: 5px;
        padding-bottom: 5px;
        MyText {
            vertical-alignment: center;
            horizontal-alignment: center;
            text: text;
        }
    }
}

export component OtaDisplay inherits Rectangle {
    // width: 480px;
    VerticalLayout {

        alignment: start;

        HorizontalLayout {
            RectText {
              background: white;
            }
            RectText {
                background: skyblue;
                width: 190px;
                text: "Console";
            }
            RectText {
                background: skyblue;
                width: 190px;
                text: "Scale";
            }
        }

        Rectangle {
            background: white;
            VerticalLayout {
                HorizontalLayout {
                    height: 56px;
                    RectText {
                        text: "Installed";
                    }
                    RectText {
                        width: 190px;
                        text: AppState.firmwares.console-curr;
                    }

                    RectText {
                        width: 190px;
                        text: AppState.firmwares.scale-curr;
                    }
                }
            }
        }

        Rectangle {
            background: white;
            width: parent.width;
            border-color: black;
            border-width: 1px;
            VerticalLayout {

                HorizontalLayout {
                    RectText {
                        width: 100px;
                        text: "Stable";
                    }
                    MyButton {
                        width: 190px;
                        height: 56px;
                        text: (AppState.firmwares.console-stable-newer ? "Update to\n" : "") + AppState.firmwares.console-stable;
                        enabled: AppState.firmwares.console-stable-newer;
                        clicked => {
                            FrameworkState.ota-state = OtaState.Started;
                            FrameworkState.ota-allow-close-during-update = false;
                            AppBackend.ota_update_firmware("console", "stable");
                        }
                    }

                    MyButton {
                        width: 190px;
                        height: 56px;
                        text: (AppState.firmwares.scale-stable-newer ? "Update to\n" : "") + AppState.firmwares.scale-stable;
                        enabled: AppState.firmwares.scale-stable-newer;
                        clicked => {
                            FrameworkState.ota-state = OtaState.Started;
                            FrameworkState.ota-allow-close-during-update = true;
                            AppBackend.ota_update_firmware("scale", "stable");
                        }
                    }
                }

                HorizontalLayout {
                    RectText {
                        width: 100px;
                        text: "Beta";
                    }
                    MyButton {
                        width: 190px;
                        height: 56px;
                        text: (AppState.firmwares.console-unstable-newer ? "Update to\n" : "") + AppState.firmwares.console-unstable;
                        enabled: AppState.firmwares.console-unstable-newer;
                        clicked => {
                            FrameworkState.ota-state = OtaState.Started;
                            FrameworkState.ota-allow-close-during-update = false;
                            AppBackend.ota_update_firmware("console", "unstable");
                        }
                    }

                    MyButton {
                        width: 190px;
                        height: 56px;
                        text: (AppState.firmwares.scale-unstable-newer ? "Update to\n" : "") + AppState.firmwares.scale-unstable;
                        enabled: AppState.firmwares.scale-unstable-newer;
                        clicked => {
                            FrameworkState.ota-state = OtaState.Started;
                            FrameworkState.ota-allow-close-during-update = true;
                            AppBackend.ota_update_firmware("scale", "unstable");
                        }
                    }
                }
            }
        }
    }
}

export component AppOtaSelect inherits Rectangle {
    background: white;
    // height: 320px;
    VerticalLayout {
        Title {
            text: "Over the Air Network Software Update";
        }

        // if FrameworkState.ota-state == OtaState.Checking: OtaCheck { }
        if FrameworkState.ota-state == OtaState.UserInput: OtaDisplay { }
        if FrameworkState.ota-state != OtaState.Started: MyButton {
            height: 56px;
            text: "Cancel";
            clicked => {
                FrameworkState.ota-state = OtaState.NotStarted
            }
        }
    }

    property <OtaState> ota_state;


}
