import { MyText, MyButton, ButtonType, WizardButtons, Title } from "framework/widgets.slint";
import { AppBackend, AppState, ControlState, SpoolStagingState, SpoolScaleState, StagingOperationsPage, UiSpoolRecordDisplay } from "app.slint";
import { SpoolDisplay } from "spool-display.slint";
import { Utils } from "utils.slint";
import { ScaleWeightDisplay } from "app-widgets.slint";

component SpoolDisplayStep inherits Rectangle {
    callback more-clicked();
    in property <UiSpoolRecordDisplay> spool-display;
    VerticalLayout {

        SpoolDisplay {
            spool-display: root.spool-display;
        }

        HorizontalLayout {
            height: 56px;
            if AppState.spool-scale-state != SpoolScaleState.NotAvailable: MyButton {
                enabled: AppState.spool-staging-state != SpoolStagingState.Empty && AppState.is-scale-usable-now();
                text: "Update Weight";
                clicked => {
                    AppState.staging-operation-page = StagingOperationsPage.UpdateWeight;
                }
            }

            if AppState.spool-scale-state == SpoolScaleState.NotAvailable: MyButton {
                text: "Configure Slot";
                clicked => {
                    AppState.control-state = ControlState.TraySelect;
                }
            }

            MyButton {
                text: "More...";
                clicked => {
                    AppState.staging-operation-page = StagingOperationsPage.OperationSelection;
                }
            }

            MyButton {
                text: "Close";
                clicked => {
                    AppState.prompt-select-tray();
                }
            }
        }
    }
}

component OperationSelectionStep inherits Rectangle {
    background: white;
    VerticalLayout {
        Title {
            text: "Please Select Staging Operation";
        }

        GridLayout {
            padding: 5px;
            spacing: 5px;
            Row {
                MyButton {
                    enabled: AppState.spool-staging-state != SpoolStagingState.Empty && AppState.is-scale-usable-now();
                    text: "Update Weight";
                    clicked => {
                        AppState.staging-operation-page = StagingOperationsPage.UpdateWeight;
                    }
                }

                MyButton {
                    text: "Configure Slot Manually";
                    clicked => {
                        AppState.control-state = ControlState.TraySelect;
                    }
                }

                MyButton {
                    text: "Clear Staging";
                    clicked => {
                        AppBackend.clear-staging();
                    }
                }
            }

            Row {
                MyButton {
                    text: "Encode Tag";
                    clicked => {
                        AppState.encode-start();
                    }
                }

                MyButton {
                    text: "Unlink Tag";
                    clicked => {
                        AppBackend.unlink-spool-from-tag(AppState.spool-staging-info.id)
                    }
                }

                MyButton {
                    text: "Erase Tag";
                    clicked => {
                        AppBackend.erase-tag-by-spool-id(AppState.spool-staging-info.id);
                        AppState.control-state = ControlState.Ready;
                    }
                }
            }

            Row {
                MyButton {
                    enabled: false;
                    text: "Mark as Dried";
                }

                MyButton {
                    // for used up spools it needs to show "mark refilled", and start process of weighting;
                    // used up should clear the weights/fill the used, and mark it as used etc.
                    enabled: false;
                    text: "Mark Used-Up";
                }
            }
        }

        HorizontalLayout {
            MyButton {
                height: 56px;
                text: "Cancel";
                clicked => {
                    AppState.control-state = ControlState.Ready;
                }
            }
        }
    }
}

enum UpdateWeightSelect {
  None,
  UsedKeepNew,
  Unused,
  UsedClearNew
}


component UpdateWeightPage inherits Rectangle {
    height: 320px;
    width: 480px;
    in-out property <bool> unused: unused.pushed;
    in property <int> weight-current: 1;
    in property <int> weight-new: 1;
    in property <string> spool-id;
    property <UpdateWeightSelect> update-weight-select: weight-current != 0 ? UsedKeepNew : None;
    background: white;
    function pressed(operation: UpdateWeightSelect) {
        update-weight-select = operation;
    }
    VerticalLayout {
        Title {
            text: "Update Spool \{spool-id} Weight";
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            spacing: 8px;

            Rectangle {
                VerticalLayout {
                    spacing: 8px;
                    Rectangle {
                        MyText {
                            width: parent.width;
                            text: "Please place the spool on the scale:";
                            wrap: word-wrap;
                        }
                    }

                    HorizontalLayout {
                        alignment: center;
                        scale-display := ScaleWeightDisplay {
                            weight-display-content: Gross;
                            width: 160px;
                        }
                    }

                    MyText {
                        width: parent.width;
                        text: "Then select how to update weight(s):";
                    }

                    // TODO: default based on backend info (need to add to encode-request/display the added-as-new)
                    HorizontalLayout {
                        x: - 5px;
                        width: parent.width + 10px;
                        height: 86px;
                        used := MyButton {
                            type: RadioButton;
                            text: weight-new != 0 ? "Used\n\nKeep Full Weight" : "Used";
                            pushed: update-weight-select == UpdateWeightSelect.UsedKeepNew;
                            clicked => {
                                root.pressed(UpdateWeightSelect.UsedKeepNew);
                            }
                        }

                        unused := MyButton {
                            type: RadioButton;
                            text: "Full/Unused\n\nSet Full Weight";
                            pushed: update-weight-select == UpdateWeightSelect.Unused;
                            clicked => {
                                root.pressed(UpdateWeightSelect.Unused);
                            }
                        }

                        if weight-new != 0: clear-new-weight := MyButton {
                            type: RadioButton;
                            text: "Used\n\nClear Full Weight";
                            pushed: update-weight-select == UpdateWeightSelect.UsedClearNew;
                            clicked => {
                                root.pressed(UpdateWeightSelect.UsedClearNew);
                            }
                        }
                    }
                }
            }
        }

        WizardButtons {
            back-enabled: true;
            next-enabled: scale-display.stable-weight && update-weight-select != UpdateWeightSelect.None;
            cancel-enabled: true;
            next-text: "Update Weight";
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
            next-clicked => {
                if root.update-weight-select == UpdateWeightSelect.UsedKeepNew {
                    AppBackend.set-spool-weight(root.spool-id, AppState.spool-scale-weight, -1, false);
                } else if root.update-weight-select == UpdateWeightSelect.Unused {
                    AppBackend.set-spool-weight(root.spool-id, AppState.spool-scale-weight, AppState.spool-scale-weight, false);
                } else if root.update-weight-select == UpdateWeightSelect.UsedClearNew {
                    AppBackend.set-spool-weight(root.spool-id, AppState.spool-scale-weight, 0, false);
                }
            }
            back-clicked => {
                AppState.staging-operation-page = StagingOperationsPage.SpoolDisplay;
            }
        }
    }
}

export component StagingOperations {
    property <UiSpoolRecordDisplay> spool-display: AppBackend.get-spool-record-display(AppState.spool-staging-info.id);
    if AppState.staging-operation-page == StagingOperationsPage.SpoolDisplay: SpoolDisplayStep {
        spool-display: spool-display;
    }
    if AppState.staging-operation-page == StagingOperationsPage.OperationSelection: OperationSelectionStep { }
    if AppState.staging-operation-page == StagingOperationsPage.UpdateWeight: UpdateWeightPage {
        weight-current: spool-display.spool-record.weight-current;
        weight-new: spool-display.spool-record.weight-new;
        spool-id: spool-display.spool-record.id;
    }
}
