name: Build SpoolEase
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev cmake gcc-riscv64-unknown-elf libssl-dev pkg-config libuv1-dev

      - name: Setup ESP Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: true

      - name: Build and Merge Binary
        working-directory: ./core
        run: |
          if [ -f "cargo.toml" ]; then mv cargo.toml Cargo.toml; fi
          rm -f rust-toolchain.toml
          # Instalujemy narzędzie espflash, które zrobi "czystą" binarkę
          cargo install espflash --no-default-features --features cli --version 2.1.0
          # Ta komenda tworzy plik merged.bin, który ma w sobie wszystko (0x0)
          cargo espflash save-image --release --target xtensa-esp32s3-none-elf ../merged.bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpoolEase-Final-PL
          path: merged.bin
